import { ParseStatementResponse } from '@/types';

export const SAMPLE_STATEMENT_DATA: ParseStatementResponse = {
  header: {
    issuer: 'HDFC Bank',
    card_last_4: '4821',
    statement_period_start: '2026-07-15',
    statement_period_end: '2026-08-14',
    total_amount_due: '45230.50',
    minimum_amount_due: '2265.00',
    payment_due_date: '2026-09-04',
    credit_limit: '250000.00',
    available_credit: '204769.50',
    opening_balance: '0.00',
    total_debits: '45230.50',
    total_credits: '0.00',
  },
  transactions: [
    {
      transaction_date: '2026-07-16',
      post_date: '2026-07-17',
      merchant_raw: 'SWIGGY BANGALORE IND',
      merchant_normalized: 'Swiggy',
      amount: '549.00',
      transaction_type: 'PURCHASE',
      category: 'Food & Dining',
      subcategory: 'Online Food Delivery',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 1,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-07-18',
      post_date: '2026-07-19',
      merchant_raw: 'AMAZON PAY INDIA PVT LTD',
      merchant_normalized: 'Amazon',
      amount: '12499.00',
      transaction_type: 'PURCHASE',
      category: 'Shopping',
      subcategory: 'E-Commerce',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 1,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-07-21',
      post_date: '2026-07-22',
      merchant_raw: 'BLINKIT GROCERY NEW DELHI',
      merchant_normalized: 'Blinkit',
      amount: '384.50',
      transaction_type: 'PURCHASE',
      category: 'Groceries & Quick-Commerce',
      subcategory: 'Quick Commerce',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 1,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-07-23',
      post_date: '2026-07-24',
      merchant_raw: 'NETFLIX ENTERTAINMENT SVCS',
      merchant_normalized: 'Netflix',
      amount: '649.00',
      transaction_type: 'PURCHASE',
      category: 'Subscriptions',
      subcategory: 'Streaming Video',
      tier: 1,
      is_recurring: true,
      currency: 'INR',
      source_page: 1,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-07-26',
      post_date: '2026-07-27',
      merchant_raw: 'ZOMATO RESTAURANT GURGAON',
      merchant_normalized: 'Zomato',
      amount: '1420.00',
      transaction_type: 'PURCHASE',
      category: 'Food & Dining',
      subcategory: 'Dining Out',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 1,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-07-29',
      post_date: '2026-07-30',
      merchant_raw: 'UBER INDIA TECH PVT LTD',
      merchant_normalized: 'Uber',
      amount: '680.00',
      transaction_type: 'PURCHASE',
      category: 'Transport & Fuel',
      subcategory: 'Rideshare',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 1,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-08-02',
      post_date: '2026-08-03',
      merchant_raw: 'SPOTIFY INDIA MUMBAI',
      merchant_normalized: 'Spotify',
      amount: '119.00',
      transaction_type: 'PURCHASE',
      category: 'Subscriptions',
      subcategory: 'Music Streaming',
      tier: 1,
      is_recurring: true,
      currency: 'INR',
      source_page: 2,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-08-05',
      post_date: '2026-08-06',
      merchant_raw: 'AIRTEL PREPAID RECHARGE',
      merchant_normalized: 'Airtel',
      amount: '999.00',
      transaction_type: 'PURCHASE',
      category: 'Bills & Utilities',
      subcategory: 'Telecom',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 2,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-08-09',
      post_date: '2026-08-10',
      merchant_raw: 'CROMA ELECTRONICS MUMBAI',
      merchant_normalized: 'Croma',
      amount: '24900.00',
      transaction_type: 'PURCHASE',
      category: 'Shopping',
      subcategory: 'Electronics',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 2,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-08-12',
      post_date: '2026-08-13',
      merchant_raw: 'ZEPTO CONSUMER GOODS',
      merchant_normalized: 'Zepto',
      amount: '230.00',
      transaction_type: 'PURCHASE',
      category: 'Groceries & Quick-Commerce',
      subcategory: 'Quick Commerce',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 2,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-08-13',
      post_date: '2026-08-14',
      merchant_raw: 'STARBUCKS COFFEE KORAMANGALA',
      merchant_normalized: 'Starbucks',
      amount: '450.00',
      transaction_type: 'PURCHASE',
      category: 'Food & Dining',
      subcategory: 'Cafe',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 2,
      confidence_score: 1.0,
    },
    {
      transaction_date: '2026-08-14',
      post_date: '2026-08-14',
      merchant_raw: 'HPCL FUEL STATION BANGALORE',
      merchant_normalized: 'HPCL',
      amount: '3000.00',
      transaction_type: 'PURCHASE',
      category: 'Transport & Fuel',
      subcategory: 'Fuel',
      tier: 1,
      is_recurring: false,
      currency: 'INR',
      source_page: 2,
      confidence_score: 1.0,
    },
  ],
  raw_text_length: 3420,
  reconciliation_status: 'VALIDATED',
  reconciliation_discrepancy: '0.00',
  reconciliation: {
    status: 'VALIDATED',
    discrepancy: '0.00',
    extracted_debits: '45230.50',
    extracted_credits: '0.00',
    statement_total_debits: '45230.50',
    statement_total_credits: '0.00',
    statement_total_amount_due: '45230.50',
    expected_total_due: '45230.50',
    is_balanced: true,
    unparsed_lines_count: 0,
    warnings: [],
  },
  validation: {
    is_valid: true,
    issues: [],
    duplicate_count: 0,
    flagged_count: 0,
  },
  categorization_stats: {
    total_transactions: 12,
    tier1_matches: 12,
    tier2_matches: 0,
    tier3_matches: 0,
    cached_matches: 0,
    hit_rate: 1.0,
  },
  analytics: {
    spend_metrics: {
      total_debits: '45230.50',
      total_credits: '0.00',
      net_spend: '45230.50',
      total_transaction_count: 12,
      debit_transaction_count: 12,
      credit_transaction_count: 0,
      average_transaction_amount: '3769.21',
      median_transaction_amount: '664.50',
      max_transaction_amount: '24900.00',
      min_transaction_amount: '119.00',
    },
    category_breakdown: [
      {
        category: 'Shopping',
        total_amount: '37399.00',
        percentage: 82.68,
        transaction_count: 2,
        average_amount: '18699.50',
        top_merchants: ['Croma', 'Amazon'],
      },
      {
        category: 'Transport & Fuel',
        total_amount: '3680.00',
        percentage: 8.14,
        transaction_count: 2,
        average_amount: '1840.00',
        top_merchants: ['HPCL', 'Uber'],
      },
      {
        category: 'Food & Dining',
        total_amount: '2419.00',
        percentage: 5.35,
        transaction_count: 3,
        average_amount: '806.33',
        top_merchants: ['Zomato', 'Swiggy', 'Starbucks'],
      },
      {
        category: 'Bills & Utilities',
        total_amount: '999.00',
        percentage: 2.21,
        transaction_count: 1,
        average_amount: '999.00',
        top_merchants: ['Airtel'],
      },
      {
        category: 'Subscriptions',
        total_amount: '768.00',
        percentage: 1.70,
        transaction_count: 2,
        average_amount: '384.00',
        top_merchants: ['Netflix', 'Spotify'],
      },
      {
        category: 'Groceries & Quick-Commerce',
        total_amount: '614.50',
        percentage: 1.36,
        transaction_count: 2,
        average_amount: '307.25',
        top_merchants: ['Blinkit', 'Zepto'],
      },
    ],
    merchant_concentration: [
      {
        merchant_name: 'Croma',
        category: 'Shopping',
        total_amount: '24900.00',
        percentage: 55.05,
        transaction_count: 1,
      },
      {
        merchant_name: 'Amazon',
        category: 'Shopping',
        total_amount: '12499.00',
        percentage: 27.63,
        transaction_count: 1,
      },
      {
        merchant_name: 'HPCL',
        category: 'Transport & Fuel',
        total_amount: '3000.00',
        percentage: 6.63,
        transaction_count: 1,
      },
      {
        merchant_name: 'Zomato',
        category: 'Food & Dining',
        total_amount: '1420.00',
        percentage: 3.14,
        transaction_count: 1,
      },
      {
        merchant_name: 'Airtel',
        category: 'Bills & Utilities',
        total_amount: '999.00',
        percentage: 2.21,
        transaction_count: 1,
      },
      {
        merchant_name: 'Netflix',
        category: 'Subscriptions',
        total_amount: '649.00',
        percentage: 1.43,
        transaction_count: 1,
      },
      {
        merchant_name: 'Uber',
        category: 'Transport & Fuel',
        total_amount: '680.00',
        percentage: 1.50,
        transaction_count: 1,
      },
      {
        merchant_name: 'Swiggy',
        category: 'Food & Dining',
        total_amount: '549.00',
        percentage: 1.21,
        transaction_count: 1,
      },
      {
        merchant_name: 'Starbucks',
        category: 'Food & Dining',
        total_amount: '450.00',
        percentage: 0.99,
        transaction_count: 1,
      },
      {
        merchant_name: 'Blinkit',
        category: 'Groceries & Quick-Commerce',
        total_amount: '384.50',
        percentage: 0.85,
        transaction_count: 1,
      },
    ],
    temporal_metrics: {
      daily_spending: [
        { date: '2026-07-16', amount: '549.00', transaction_count: 1, cumulative_amount: '549.00' },
        { date: '2026-07-18', amount: '12499.00', transaction_count: 1, cumulative_amount: '13048.00' },
        { date: '2026-07-21', amount: '384.50', transaction_count: 1, cumulative_amount: '13432.50' },
        { date: '2026-07-23', amount: '649.00', transaction_count: 1, cumulative_amount: '14081.50' },
        { date: '2026-07-26', amount: '1420.00', transaction_count: 1, cumulative_amount: '15501.50' },
        { date: '2026-07-29', amount: '680.00', transaction_count: 1, cumulative_amount: '16181.50' },
        { date: '2026-08-02', amount: '119.00', transaction_count: 1, cumulative_amount: '16300.50' },
        { date: '2026-08-05', amount: '999.00', transaction_count: 1, cumulative_amount: '17299.50' },
        { date: '2026-08-09', amount: '24900.00', transaction_count: 1, cumulative_amount: '42199.50' },
        { date: '2026-08-12', amount: '230.00', transaction_count: 1, cumulative_amount: '42429.50' },
        { date: '2026-08-13', amount: '450.00', transaction_count: 1, cumulative_amount: '42879.50' },
        { date: '2026-08-14', amount: '3000.00', transaction_count: 1, cumulative_amount: '45230.50' },
      ],
      weekday_spend: '5911.50',
      weekend_spend: '39319.00',
      weekday_percentage: 13.07,
      weekend_percentage: 86.93,
      avg_daily_burn_rate: '1507.68',
      day_of_week_breakdown: {
        Monday: '0.00',
        Tuesday: '614.50',
        Wednesday: '1679.00',
        Thursday: '1648.00',
        Friday: '3000.00',
        Saturday: '12499.00',
        Sunday: '26439.00',
      },
    },
    micro_spend_metrics: {
      threshold: '250.00',
      count: 2,
      total_amount: '349.00',
      percentage_of_transactions: 16.67,
      percentage_of_spend: 0.77,
      top_micro_merchants: ['Spotify', 'Zepto'],
    },
    recurring_analysis: {
      items: [
        {
          merchant_name: 'Netflix',
          category: 'Subscriptions',
          amount: '649.00',
          frequency: 'Monthly',
          occurrences: 1,
          annualized_cost: '7788.00',
          transaction_dates: ['2026-07-23'],
        },
        {
          merchant_name: 'Spotify',
          category: 'Subscriptions',
          amount: '119.00',
          frequency: 'Monthly',
          occurrences: 1,
          annualized_cost: '1428.00',
          transaction_dates: ['2026-08-02'],
        },
      ],
      total_monthly_recurring: '768.00',
      total_annual_recurring: '9216.00',
      recurring_percentage_of_spend: 1.70,
    },
  },
  anomalies: {
    findings: [
      {
        id: 'finding-01',
        detector_type: 'MERCHANT_CONCENTRATION',
        severity: 'CRITICAL',
        title: 'High Single-Merchant Concentration on Croma',
        description: 'Single purchase on Croma accounted for 55.1% (₹24,900.00) of total cycle debits.',
        evidence: {
          current_value: '55.05%',
          threshold_or_baseline: '35.0%',
          delta_percentage: 20.05,
          related_category: 'Shopping',
          related_merchants: ['Croma'],
          transaction_count: 1,
        },
        impact_amount: '24900.00',
        actionable: false,
      },
      {
        id: 'finding-02',
        detector_type: 'WEEKEND_SPIKE',
        severity: 'HIGH',
        title: 'Severe Weekend Spending Skew (86.9% of Total Billed)',
        description: 'Weekend purchases totaled ₹39,319.00 across high-ticket electronics and lifestyle spending.',
        evidence: {
          current_value: '86.93%',
          threshold_or_baseline: '55.0%',
          delta_percentage: 31.93,
          related_category: 'Shopping',
          related_merchants: ['Croma', 'Amazon', 'Zomato'],
          transaction_count: 3,
        },
        impact_amount: '39319.00',
        actionable: true,
      },
      {
        id: 'finding-03',
        detector_type: 'FREQUENT_SMALL_SPEND',
        severity: 'MEDIUM',
        title: 'Micro-Spending Overhead on Delivery & Quick-Commerce',
        description: 'Frequent small orders under ₹500 across food and grocery delivery create avoidable platform overhead.',
        evidence: {
          current_value: '16.67%',
          threshold_or_baseline: '10.0%',
          delta_percentage: 6.67,
          related_category: 'Groceries & Quick-Commerce',
          related_merchants: ['Zepto', 'Blinkit', 'Swiggy'],
          transaction_count: 4,
        },
        impact_amount: '1563.50',
        actionable: true,
      },
      {
        id: 'finding-04',
        detector_type: 'SUBSCRIPTION_BURDEN',
        severity: 'LOW',
        title: 'Active Digital Subscriptions Total ₹9,216 Annual Burden',
        description: '2 recurring media services detected (Netflix Premium & Spotify Individual).',
        evidence: {
          current_value: '₹768.00/mo',
          threshold_or_baseline: null,
          delta_percentage: null,
          related_category: 'Subscriptions',
          related_merchants: ['Netflix', 'Spotify'],
          transaction_count: 2,
        },
        impact_amount: '9216.00',
        actionable: true,
      },
    ],
    total_findings_count: 4,
    critical_count: 1,
    high_count: 1,
    medium_count: 1,
    low_count: 1,
  },
  recommendations: {
    recommendations: [
      {
        id: 'rec-01',
        finding_id: 'finding-02',
        type: 'WEEKEND_PACING',
        title: 'Institute a 48-Hour Weekend Cooling-off Period',
        reason: 'Over 86.9% of spending was concentrated on weekends, driven primarily by large spontaneous electronic and e-commerce purchases.',
        evidence: {
          current_spend: '39319.00',
          historical_avg: '18000.00',
          transaction_count: 3,
          top_merchants: ['Croma', 'Amazon'],
          excess_amount: '21319.00',
          savings_calculation_basis: 'Delaying non-essential discretionary electronics purchases by 48 hours avoids impulse buys.',
        },
        estimated_monthly_savings: '2500.00',
        confidence_score: 0.92,
        action: 'Add large electronic items to wishlist and wait 48 hours before swiping card.',
        priority: 1,
        target_category: 'Shopping',
        status: 'ACTIVE',
      },
      {
        id: 'rec-02',
        finding_id: 'finding-03',
        type: 'MICRO_SPEND_CONSOLIDATION',
        title: 'Consolidate Quick-Commerce & Food Delivery Orders',
        reason: 'Multiple small basket purchases on Zepto and Swiggy incurred recurring delivery surcharges and surge fees.',
        evidence: {
          current_spend: '1563.50',
          historical_avg: '800.00',
          transaction_count: 4,
          top_merchants: ['Zepto', 'Blinkit', 'Swiggy'],
          excess_amount: '763.50',
          savings_calculation_basis: 'Consolidating into 2 weekly planned grocery baskets over ₹1,000 saves delivery fees and impulse additions.',
        },
        estimated_monthly_savings: '650.00',
        confidence_score: 0.88,
        action: 'Schedule 2 fixed weekly grocery replenishment deliveries above ₹1,000.',
        priority: 2,
        target_category: 'Groceries & Quick-Commerce',
        status: 'ACTIVE',
      },
      {
        id: 'rec-03',
        finding_id: 'finding-04',
        type: 'SUBSCRIPTION_AUDIT',
        title: 'Audit Active Streaming Subscriptions for Dual Redundancy',
        reason: 'You are currently paying for multiple standalone entertainment streaming platforms totaling ₹768/mo.',
        evidence: {
          current_spend: '768.00',
          historical_avg: null,
          transaction_count: 2,
          top_merchants: ['Netflix', 'Spotify'],
          excess_amount: '300.00',
          savings_calculation_basis: 'Switching to annual plans or bundling media memberships.',
        },
        estimated_monthly_savings: '300.00',
        confidence_score: 0.85,
        action: 'Review Spotify vs Apple Music bundle and switch to annual subscription billing.',
        priority: 3,
        target_category: 'Subscriptions',
        status: 'ACTIVE',
      },
    ],
    total_potential_monthly_savings: '3450.00',
    recommendations_count: 3,
    high_impact_count: 2,
  },
  explanation: {
    executive_summary:
      'Your HDFC Bank statement was mathematically reconciled with 100% precision (Extracted Debits ₹45,230.50 match total statement charges with ₹0.00 discrepancy). Spending was heavily skewed toward Shopping (82.7%, primarily a major ₹24,900 Croma appliance purchase and ₹12,499 Amazon order). 86.9% of spending occurred over weekends. By consolidating quick-commerce baskets and instituting a 48-hour delay rule on large discretionary buys, you can realistically retain ₹3,450.00 / month.',
    what_stands_out: [
      {
        finding_title: 'Weekend Spend Inflation (86.9%)',
        observation: 'Discretionary and large asset shopping is almost exclusively occurring on Saturdays and Sundays.',
        urgency: 'Immediate Action',
      },
      {
        finding_title: 'Single Merchant Concentration',
        observation: '55.1% of card debits went to a single Croma transaction, dominating the billing cycle.',
        urgency: 'This Month',
      },
      {
        finding_title: 'Micro-Spend Quick Commerce Leaks',
        observation: '4 low-value orders on Blinkit/Zepto/Swiggy added avoidable service fee overhead.',
        urgency: 'Good Habit',
      },
    ],
    action_steps: [
      {
        step_number: 1,
        title: 'Institute 48-Hour Weekend Cooling-off Rule',
        description: 'For any discretionary electronic purchase above ₹5,000, wait 48 hours to confirm necessity before charging to credit card.',
        estimated_impact: '₹2,500/mo',
      },
      {
        step_number: 2,
        title: 'Batch Quick-Commerce Orders into 2 Weekly Deliveries',
        description: 'Combine daily micro-orders on Blinkit and Zepto into two scheduled weekly bulk grocery orders over ₹1,000.',
        estimated_impact: '₹650/mo',
      },
      {
        step_number: 3,
        title: 'Optimize Digital Subscriptions to Annual Billing',
        description: 'Convert Netflix and Spotify to family or annual plans to save up to 20% on recurring digital media.',
        estimated_impact: '₹300/mo',
      },
    ],
    coaching_tone_note: 'Constructive, direct, and mathematically grounded.',
    generated_by: 'Deterministic Rules & Hybrid Gemini Explainer',
    is_fallback: false,
  },
  unparsed_lines: [],
};
